:::::::::::::::::::::::::: {#content}
[Saltar la navegación](#main){.sr-av}

:::: {#header}
::: {#headerContent}
Estructuras
:::
::::

- [Circuitos de Corriente Alterna](index.html){.daddy .main-node}
- [1. Corriente alterna.](1_corriente_alterna.html){.no-ch}
- [2. Representación de señales sinusoidales.](2_representacin_de_seales_sinusoidales.html){.no-ch}
- [[3. Respuesta de los componentes básicos a la CA.](3_respuesta_de_los_componentes_bsicos_a_la_ca.html){.active .no-ch}]{#active}
- [4. Impedancia. Ley de Ohm generalizada.](4_impedancia_ley_de_ohm_generalizada.html){.no-ch}
- [5. Circuitos RLC](5_circuitos_rlc.html){.no-ch}
- [6. Potencia en Corriente Alterna](6_potencia_en_corriente_alterna.html){.no-ch}

::: {#topPagination}
[« Anterior](2_representacin_de_seales_sinusoidales.html){.prev} [\| ]{.sep}[Siguiente »](4_impedancia_ley_de_ohm_generalizada.html){.next}
:::

::::::::::::::::::::: {#main-wrapper}
:::::::::::::::::::: {#main .section}
::: {#nodeDecoration}
# 3. Respuesta de los componentes básicos a la CA. {#nodeTitle}
:::

::::::::::: {.iDevice .emphasis1}
::: {.iDevice_header .iDevice_header_noIcon}
# Respuesta de una resistencia {#respuesta-de-una-resistencia .iDeviceTitle}
:::

::::::::: iDevice_inner
:::::::: iDevice_content_wrapper
::::::: {#ta164_161_2 .block .iDevice_content}
:::::: {.exe-udlContent .exe-udlContent-representation}
::::: {.section .exe-udlContent-block}
:::: exe-udlContent-content
::: exe-udlContent-content-main
Si a una resistencia de valor R ohmios (Ω) se la somete a una tensión sinusoidal de [**valor eficaz U**]{style="color: #008000;"} y [**pulsación**]{style="color: #008000;"}

[**ω**]{style="color: #008000;"}, la tensión instantánea aplicada a la resistencia es:

и(t)= U.V2)-sen(c-t+q)

Según la ley de Ohm, tenemos que i(t) = u(t)/ R, y por tanto, la intensidad instantánea que circula por la

resistencia es:

U.V2

i(t) =

• sen(@•t +Ф)

R

Analicemos este resultado; la intensidad obtenida tiene la misma pulsación que la tensión y además tiene:

U.V2

Un valor de picol, = -\
. La intensidad eficaz es 1 =.\
. La misma expresión que en corriente continua.

R

• El desfase entre la tensión e intensidad es nulo, es decir, están en fase. La fase inicial de la intensidad es

Ф,=Ф.

Su representación gráfica es la mostrada en la siguiente figura:
:::
::::
:::::
::::::
:::::::
::::::::
:::::::::
:::::::::::

:::::::: {.iDevice .emphasis0}
::::::: {#ta165_162_2 .block .iDevice_content}
:::::: exe-text
::::: container
### Simulador Interactivo: Fasor y Onda Senoidal

::: controls
Fase inicial (φ): [-60]{#phiVal .label-val}°
:::

::: {#plot}
:::
:::::
::::::
:::::::
::::::::

::: {#packageLicense .cc .cc-by-nc-sa}
Obra publicada con [Licencia Creative Commons Reconocimiento No comercial Compartir igual 4.0](http://creativecommons.org/licenses/by-nc-sa/4.0/){rel="license"}
:::
::::::::::::::::::::
:::::::::::::::::::::

::: {#bottomPagination}
[« Anterior](2_representacin_de_seales_sinusoidales.html){.prev} [\| ]{.sep}[Siguiente »](4_impedancia_ley_de_ohm_generalizada.html){.next}
:::
::::::::::::::::::::::::::
