---
date: last-modified        # Captura la fecha real de la 칰ltima vez que guardaste el archivo
date-format: "DD/MM/YYYY"  # Define el formato espa침ol
page-layout: full
---

# Introducci칩n {.unnumbered}

En esta unidad de **Tecnolog칤a e Ingenier칤a II**, estudiaremos el comportamiento de los circuitos el칠ctricos cuando la tensi칩n y la corriente var칤an de forma sinusoidal en el tiempo.

## Contenidos de la unidad

A continuaci칩n, se detallan las secciones que componen esta unidad:

1. **Corriente alterna**: Conceptos b치sicos y generaci칩n.
2. **Representaci칩n de se침ales sinusoidales**: An치lisis trigonom칠trico y fasorial.
3. **Respuesta de los componentes b치sicos**: Comportamiento de R, L y C.
4. **Impedancia**: La ley de Ohm en el dominio complejo.
5. **Circuitos RLC**: An치lisis de asociaciones serie y paralelo.
6. **Potencia en CA**: Estudio del factor de potencia y eficiencia energ칠tica.

::: {.content-visible when-format="html"}

::: {.callout-note appearance="simple"}
## 游닄 Material de estudio
Puedes descargar esta unidad completa en formato PDF para estudiar sin conexi칩n o imprimirla:



[Descargar PDF](Unidad_6_Circuitos_CA.pdf){.btn .btn-primary .btn-lg role="button"}
:::

:::


*칔ltima actualizaci칩n: {{< meta date >}}*
